### ISSUE TITLE
Error in LolEvt.py

### ISSUE THREAD

**Issue by gis-bern** [Ludwig-K/QGisLinearReference#4]
Hallo 

it looks like in line 1296 of LolEvt.py, there should be "update_ref_pk" instead of "insert_ref_pk".
This caused the problem for us to update features on multi-lines.
We fixed it locally and now we can also update our multi-lines.

**Comment by Ludwig-K** [comment]
I just (2024-09-26) uploaded the new version 2.0.0 to 
https://plugins.qgis.org/plugins/LinearReferencing/

Completely rebuilt, took a little longer, sorry!

Should soon be approved by QGis maintainers and downloadable.

Your bug should be removed, but possibly there are some new ones...

Please check and report any issues!
