### ISSUE TITLE
Cannot reduce length of base line 

### ISSUE THREAD

**Issue by hobbesh** [Ludwig-K/QGisLinearReference#5]
We cannot reduce a line correctly in the base network if a data layer already references on it. This is due to the absolut values saved in the measure_from and measure_to instead of the percentage values. The error is not vissible in the view-layer but the values are not correct any more. ST_LineSubstring (in PostGIS) expects values from 0-1 in the second and third parameter, but if the measures from the data layer are longer than the line of the base network, we have values >1.

basic insert:
![grafik](https://github.com/user-attachments/assets/f2a9e27d-3bfa-4a47-9614-69fec795ff1d)

--> change of length of base layer

SQL:
SELECT data_lyr.id as "upabs_id",
data_lyr.line_ref_id as "line_ref_id",
 data_lyr.measure_from as "measure_from",
 data_lyr.measure_to as "measure_to",
 data_lyr.offset as "offset",
ref_lyr.geom, st_length(ref_lyr.geom),
least(data_lyr."measure_from"::float,data_lyr."measure_to"::float)/st_length(ref_lyr.geom) as from,
 		greatest(data_lyr."measure_from"::float,data_lyr."measure_to"::float)/st_length(ref_lyr.geom) as to
FROM  lrs.lol_data_layer1 as data_lyr
  INNER JOIN lrs.lol_base_network as ref_lyr ON data_lyr.line_ref_id = ref_lyr.id
  where data_lyr.id=8;

--> values in the join:
![grafik](https://github.com/user-attachments/assets/84d0e7bf-7f0c-4a08-b547-8d455490eafe)

is it possible to save the relative values (from the GUI)?

**Comment by Ludwig-K** [comment]
I just (2024-09-26) uploaded the new version 2.0.0 to 
https://plugins.qgis.org/plugins/LinearReferencing/
which supports relative stationings.

Should soon be approved by QGis maintainers and downloadable.

Please check and report any issues!

**Comment by hobbesh** [comment]
Tested successfully with the new option of relative values: Reducing the length of the base-network lines worked.
thanks!
